version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_redis
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379

  app:
    image: springboot-redis-mysql-app:latest
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql-db
      - redis

volumes:
  mysql-data:
  redis-data:

networks:
  app-network:
    name: app-network
    driver: bridge